AllCops:
  NewCops: enable
  Exclude:
    - spec/support/spec_helper.rb
    - spec/rails_helper.rb
    - db/**/*
    - docs/**/*
    - config/**/*
    - bin/**/*

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*