# fly.toml file generated for twire-redis on 2022-07-18T16:57:36-03:00

app = "twire-redis"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "flyio/redis:6.2.6"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[mounts]]
  destination = "/data"
  source = "redis_server"

[[services]]